### ISSUE TITLE
Pythonanywhere Deployment Action Error

### ISSUE THREAD

**Issue by umuttopalak** [turtleship69/SubTasker#6]
Hey I check out your deployment action and it seems you didn't set the secrets. It's not working because of that

**Comment by turtleship69** [comment]
Hi, I looked into it again, I did have the secrets set but I didn't set the environment in the github action, so the script couldn't access them. 
However I decided to use a simple python script to redeploy as it allows for a bit more flexibility. Thanks for your help though, I appreciate it.  


Btw you might want to update your example script to start something like: 
```
name: Deploy pythonanywhere webapp
on: [push]
jobs:
  deploy:
    environment:
      name: 'actions'
```
(specifically the last 2 lines) so that people using your example can access the secrets from their workflows
